version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: school-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: school_db
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: school-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
